import type { Question, Speaker } from '@/types';

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 1,
    text: 'Tell me about a time you led a project through a crisis.',
    strength: 'strong',
    baselineScore: 72,
    score: 72,
    status: 'ACTIVE',
    lastScore: 72,
  },
  {
    id: 2,
    text: 'How do you handle conflicts within your team?',
    strength: 'medium',
    baselineScore: 68,
    score: 68,
    status: 'ACTIVE',
    lastScore: 68,
  },
  {
    id: 3,
    text: 'Describe your approach to professional development.',
    strength: 'strong',
    baselineScore: 75,
    score: 75,
    status: 'ACTIVE',
    lastScore: 75,
  },
  {
    id: 4,
    text: 'What metrics do you use to measure success?',
    strength: 'medium',
    baselineScore: 70,
    score: 70,
    status: 'ACTIVE',
    lastScore: 70,
  },
  {
    id: 5,
    text: 'How do you adapt to changing market conditions?',
    strength: 'strong',
    baselineScore: 73,
    score: 73,
    status: 'ACTIVE',
    lastScore: 73,
  },
  {
    id: 6,
    text: 'Tell me about your greatest achievement.',
    strength: 'weak',
    baselineScore: 76,
    score: 76,
    status: 'ACTIVE',
    lastScore: 76,
  },
  {
    id: 7,
    text: 'How do you stay updated with industry trends?',
    strength: 'weak',
    baselineScore: 65,
    score: 65,
    status: 'ACTIVE',
    lastScore: 65,
  },
  {
    id: 8,
    text: 'Describe your leadership philosophy.',
    strength: 'medium',
    baselineScore: 71,
    score: 71,
    status: 'ACTIVE',
    lastScore: 71,
  },
  {
    id: 9,
    text: 'How do you build trust with your team?',
    strength: 'strong',
    baselineScore: 74,
    score: 74,
    status: 'ACTIVE',
    lastScore: 74,
  },
  {
    id: 10,
    text: 'What attracted you to this opportunity?',
    strength: 'weak',
    baselineScore: 69,
    score: 69,
    status: 'ACTIVE',
    lastScore: 69,
  },
];

export const SPEAKERS: Speaker[] = [
  { name: 'Alex Johnson', voice: 'Professional Male' },
  { name: 'Sarah Chen', voice: 'Professional Female' },
  { name: 'Michael Brown', voice: 'Professional Male' },
];
